version: 2.1

jobs:
  fetch-dependencies:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - run:
          name: Fetch Dependencies from S3
          command: |
            aws s3 cp s3://tomcat-circleci-s3/dependencies/commons-lang3-3.12.0.jar ./dependencies/
            ls -R

  build:
    docker:
      - image: cimg/openjdk:8.0.362-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - attach_workspace:
          at: dependencies
            
      - run:
          name: Debug Directory Structure
          command: |
            ls -R
      - run:
          name: Install Custom Dependency to Local Maven Repository
          command: |
            mvn install:install-file -Dfile=dependencies/guava-32.0.1-jre.jar -DgroupId=com.google.guava -DartifactId=guava -Dversion=30.1-jre -Dpackaging=jar
            mvn install:install-file -Dfile=dependencies/commons-lang3-3.12.0.jar -DgroupId=org.apache.commons -DartifactId=commons-lang3 -Dversion=3.12.0 -Dpackaging=jar -X 
      - run:
          name: Build with Maven
          command: |
            cd src/main/java/com/myapp
            mvn clean package -DskipTests

      - persist_to_workspace:
          root: .
          paths:
            - target/my-java-project-1.0.0.jar

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to S3
          command: |
            echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
            echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
            echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
            aws s3 sync target/my-java-project-1.0.0.jar s3://tomcat-circleci-s3/

workflows:
  version: 2
  build-deploy:
    jobs:
      - fetch-dependencies
      - build:
          requires:
            - fetch-dependencies
      - deploy:
          requires:
            - build
