
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Set up Java 8 and Maven 3.9
          command: |
            java -version
            mvn -version
      - run:
          name: Build WAR File
          command: |
            cd src/main/java/com/myapp
            mvn clean package -DskipTests
      - persist_to_workspace:
          root: src/main/java/com/myapp/target
          paths:
            - my-java-project-1.0.0.jar  # Persist the built JAR for deployment

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - attach_workspace:
          at: my-java-project-1.0.0.jar

      - run:
          name: Deploy to S3
          command: |
            echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
            echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
            echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
            aws s3 sync my-java-project-1.0.0.jar s3://tomcat-circleci-s3/
        # Deploy the WAR file to the EC2 instance
      - run:
          name: Deploy to EC2 instance
          command: |
            set -x
            echo "Deploying WAR file to EC2 instance"
            scp -i $EC2_SSH_KEY my-java-project-1.0.0.jar $EC2_USERNAME@$EC2_PUBLIC_IP:/opt/tomcat/webapps/
            ssh -i $EC2_SSH_KEY $EC2_USERNAME@$EC2_PUBLIC_IP "sudo service tomcat restart"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
