version: 2.1
orbs:
   aws-cli: circleci/aws-cli@1.0.4
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Set up Java 8 and Maven 3.9
          command: |
            java -version
            mvn -version

      - run:
          name: Build WAR File
          command: |
            cd src/main/java/com/myapp
            mvn clean package -DskipTests

      - run:
          name: Deploy to S3
          command: |
            echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
            echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
            echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
            aws s3 sync ./src/main/java/com/myapp/target/ s3://tomcat-s3/

  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout

      - aws-cli/install

      - run:
          name: Configure AWS CLI
          command: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            && aws configure set default.region $AWS_DEFAULT_REGION

      - run:
          name: Download WAR Files from S3
          command: |
            # Download WAR files from S3
            aws s3 sync s3://tomcat-s3/ /path/to/destination/

            # Deploy the WAR files to Tomcat
            sudo service tomcat8 stop
            sudo rm -rf /var/lib/tomcat8/webapps/my-java-project-1.0.0*
            sudo mv /path/to/destination/*.war /var/lib/tomcat8/webapps/
            sudo service tomcat8 start

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
